

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ./.env_test
    # restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - ./.env_test
    # restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
      
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - ./.env_test
    # restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

### BONUS

  redis:
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    image: redis
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
  
  ftp:
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    image: ftp
    env_file:
      - ./.env_test
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - '21:21'
      - '21100-21110:21100-21110'


  adminer:
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
### !BONUS


volumes:
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind

  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge