services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ../.env
    # restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - ../.env
    # restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - ../.env
    # restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

volumes:
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind

  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge
